- name: rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy rabbitmq repo to repos list
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq 
      ansible.builtin.package:
        name: rabbitmq-server
        state: present
    
    - name: enable and start rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        enabled: yes
        state: started

    - name: create rabbitmq user,set password and permissions to user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        permissions:
          - configure: ".*"
            write: ".*"
            read: ".*"
        password: roboshop123
        vhost: /
        state: present