- name: configuring shipping component
  hosts: shipping
  become: yes
  tasks:
    - name: install maven and mysql
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - maven
        - mysql
    
    - name: system user setup
      ansible.builtin.user:
        name: roboshop
        home: /app
        system: yes
        shell: /sbin/nologin
        create_home: yes

    - name: create app directory
      ansible.builtin.file:
        path : /app
        state: directory
    
    - name: download url into tmp
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unzip application code to app directory
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: install dependencies using maven in app directory
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
    
    - name: install dependencies using maven in app directory
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copying service file to systemd
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: reload daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable and start service
      ansible.builtin.service:
        name: shipping
        enabled: yes
        state: started

    - name: loading data into mysql
      community.mysql.mysql_db:
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.robotshop.site
        name: all
        state: import
        target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql
        - /app/db/master-data.sql
      
    - name: restart shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
